//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.allDay = true;
        }
    
        public int Id { get; set; }
        public System.DateTime start { get; set; }
        public string title { get; set; }
        public System.DateTime end { get; set; }
        public string url { get; set; }
        public bool allDay { get; set; }
        public string textColor { get; set; }
        public string backgroundColor { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
