//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conversation()
        {
            this.isCoach = false;
        }
    
        public int Id { get; set; }
        public System.DateTime MsgDate { get; set; }
        public string Message { get; set; }
        public int ForumId { get; set; }
        public int SenderID { get; set; }
        public bool isCoach { get; set; }
    
        public virtual Forum Forum { get; set; }
    }
}
